fruits = []
f1 = input("Entre fruit name1: ")
fruits.append(f1)
f2 = input("Entre fruit name2: ")
fruits.append(f2)
f3 = input("Entre fruit name3: ")
fruits.append(f3)
f4 = input("Entre fruit name4: ")
fruits.append(f4)
f5 = input("Entre fruit name5: ")
fruits.append(f5)
f6 = input("Entre fruit name6: ")
fruits.append(f6)
f7 = input("Entre fruit name7: ")
fruits.append(f7)
f8 = input("Entre fruit name8: ")
fruits.append(f8)
f9 = input("Entre fruit name9: ")
fruits.append(f9)
f10 = input("Entre fruit name10: ")
fruits.append(f10)
print(fruits)

# by pressing alt key with up and down we can bring the text up and down