name = "Nisha"
nameshort = name[0:3]
print(nameshort)


# do alt + down or up keys to exchange the two lines


# this is string slicling 
# so basically the letters are numbered from front from 0 
# and if we backcounting it starts from -1

# here we have written [0:3]
# so the letter nubered 0 is included and every letter till 3, excluding 3



b = len(name)
print(b)
# this is how we can find the length of the string


